name: New Technology Request
description: Request to add documentation for a new technology
title: "Add technology ..."

labels: ["documentation", "new-technology"]
body:
  - type: input
    id: technology_name
    attributes:
      label: Technology Name
      placeholder: "Python"
      description: Name of the technology
    validations:
      required: true
  - type: dropdown
    id: quadrant
    attributes:
      label: Quadrant
      description: Select the appropriate quadrant
      options:
        - "0 - Languages"
        - "1 - Infrastructure"
        - "2 - Datastores"
        - "3 - Data Management"
    validations:
      required: true
  - type: dropdown
    id: ring
    attributes:
      label: Ring
      description: Select the appropriate ring
      options:
        - "0 - Adopt"
        - "1 - Trial"
        - "2 - Assess"
        - "3 - Hold"
    validations:
      required: true


  # Make the description more prominent
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A comprehensive description of the technology
      value: |
        Description of the technology. Keep it short, but make sure it includes everything needed for those who have no idea what the technology is.

        ## Pro
        * list of advantages of this technology

        ## Cons
        * list of disadvantages of this technology
      render: markdown
    validations:
      required: true

  # Add a horizontal line before metadata section
  - type: markdown
    attributes:
      value: |
        ---
        ## Metadata
        Please select the appropriate metadata values for this technology.